insert into category values(1, 'Artículos para el cuidado personal', 'Cuidado personal'), 
                           (2, 'Artículos para el hogar', 'Hogar'), 
                           (3, 'Artículos para mascotas', 'Mascotas');
                           
insert into country values(1, 'Argentina'), 
                          (2, 'Brasil'), 
                          (3, 'Colombia'), 
                          (4, 'Estados Unidos');
                          
insert into state values(1, 'Buenos Aires'), 
                        (2, 'Córdoba');
                        
insert into zip_code values(1, '1400'),
						   (2, '5000');
                           
insert into product values(1, null, false, 'Esponja facial | Konjac', 749, null, 20, 'Se recomienda cambiar la esponja cada 2 o 3 meses según su uso y cuidado.', 1),
                          (2, null, false, 'Porta Cepillo | Meraki', 450, null, 20, null, 1),
                          (3, null, true, 'Hilo dental | Orlando', 550, 470, 20, null, 1),
                          (4, 'Permiten un cuidado integral durante todo tu ciclo: garantizan una correcta respiración de la zona sin exponerla a químicos perjudiciales. Son reutilizables y compostables, con una única inversión ahorras en gastos mensuales en productos desechables.', false, 'Toallitas Femeninas de Tela | BeeGreen', 455, null, 20, null, 1),
						  (5, 'Fabricado con bambú. Tanto el mango de los cepillos como sus cajas son biodegradables y vuelven a formar parte del suelo de manera natural. El único componente no biodegradable son las cerdas, 3% del total del producto.', true, 'Cepillo de dientes | Meraki', 310, 220, 20, 'El tiempo recomendado de reemplazo del cepillo es de 2-3 meses.', 1),
                          (6, null, true, 'Afeitadora ecológica biodegradable | Eco Sustentable', 120, 100, 20, null, 1),
                          (7, 'Set de vajilla de paja de trigo biodegradable, ecológica e irrompible de 5,7 pulgadas ideal para la comida de los niños. Contiene 6 piezas de colores surtidos, es muy ligera, resistente, duradera y apta para microondas.', true, 'Juego de vajilla biodegradable 6 piezas | Oregon', 2000, 1299, 20, null, 2),
						  (8, 'Diseño moderno y elegante con estuche para llevar a donde quieras y lucirte! Libres de BPA, hechas de acero inoxidable, no tienen sabor a metal, apto para lavavajillas, reutilizables y respetuosos con el medio ambiente.', false, 'Pack de sorbetes reutilizables | Oregon',1800, null, 20, 'Modo de uso: Sacar del estuche e insertar en tu bebida favorita, luego de usar lavar con abundante agua y jabón, dejar secar en su totalidad en ambiente fresco y ventilado.', 2),
						  (9, 'Mezclando tela 100% algodón, con cera de abeja, aceite de jojoba orgánico y resina de árbol, se crea una tela lavable, REUTILIZABLE y una alternativa al plástico.', true, 'Envoltorios Reutilizables de alimentos - X 4 | BeeGreen', 2000, 1299, 20, 'Lavar en agua fría con un jabón suave. Evita las fuentes de calor, como agua caliente, sol y microondas. Secar al aire libre, y guardar en un lugar fresco.', 2),
                          (10, 'Incluyen 24 rollos/360 bolsas con 1 dispensador que se adapta a todas los tamaños. Son muy duraderas y no se fugan o rompen. Son suaves al tacto y no se pegan entre sí, lo que hace que sea fácil de abrir.', false, 'Bolsas de residuos biodegradables | Eco-Clean',300, null, 20, null, 3),
                          (11, 'Biodegradable para perros y gatos. Fabricado con fibras de bambú y almidón de maíz. Con base antideslizante para ofrecer la máxima fijación. Sin plásticos, 100% natural y disponible en 2 formatos.', true, 'Comedero para mascotas | Eco-Pet', 450, 380, 20, null, 3),
                          (12, 'Shampoo sólido para perros, 100% vegano, libre de tóxicos y no testado en animales. Evita picores y descamaciones, gracias a los efectos hidratantes y calmantes del aceite de oliva y la lavanda.', true, "Shampoo sólido | Zorro D'Avi", 390, 300, 20, null, 3),
                          (13, 'Cucha de Perro de polialuminio reciclado. Proceso de fabricación en altas temperaturas, libre de hongos y bacterias. 100% lavable y de fácil mantenimiento. Su montaje es simple y rápido. Producto 100% lavable, de fácil mantenimiento y armado.', false, "Cucha de perro mediano | Eco-cucha", 4999, null, 20, null, 3);
                          
insert into detail values(1, '100% Bambú Moso'), 
                         (2, 'Biodegradable'),
                         (3, 'Ideal para viajar'),
                         (4, 'Orificio superior e inferior para drenar agua'), 
                         (5, 'Packaging Biodegradable'),
                         (6, '100% vegano'),
                         (7, 'Carbón activado'),
                         (8, 'Sabor menta'),
                         (9, '30 metros'),
                         (10, '100% algodón'),
                         (11, '95% biodegradable y compostable'),
                         (12, 'Con alas para un mejor ajuste'),
                         (13, 'Con alas para un mejor ajuste'),
                         (14, '20 cm de largo'),
                         (15, 'Durabilidad mínima 2 años'),
                         (16, 'Máquina de afeitar biodegradable'),
                         (17, 'Material: ecológico de paja de trigo'),
                         (18, 'Se descompone despues de 90 dias'),
                         (19, 'No incluye banda lubricante'),
                         (20, '5% reciclable (hilos)'),
						 (21, 'Lavanda: para todo tipo de piel'),
                         (22, 'Antiinflamatorio y relajante'),
                         (23, 'Balancea tu PH'),
                         (24, 'Exfoliación natural'),
                         (25, 'Deja tu piel radiante y rejuvenecida');
                         
insert into products_details values(2, 1),
                                   (2, 2),
                                   (2, 3),
                                   (2, 4),
                                   (2, 5),
                                   (3, 6),
                                   (3, 2),
                                   (3, 7),
                                   (3, 8),
                                   (3, 9),
                                   (3, 5),
                                   (4, 10),
                                   (4, 11),
                                   (4, 12),
                                   (4, 14),
                                   (4, 15),
                                   (4, 20),
                                   (1, 21),
                                   (1, 22),
                                   (1, 23),
                                   (1, 24),
                                   (1, 25),
                                   (6, 16),
                                   (6, 17),
                                   (6, 18),
                                   (6, 19);		
								
insert into image values(1, 'Esponja facial', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/esponja_konjac1.png', 1, null),
						(2, 'Esponja Konjac', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/esponja_konjac3.png', 1, null),
                        (3, 'Estuche de cepillo de dientes', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/estuche_meraki.jpg', 2, null),
                        (4, 'Estuche de cepillo de dientes Meraki', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/estuche_meraki2.png', 2, null),
                        (5, 'Hilo dental de carbón activado', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/hilodental_orlando.jpg', 3, null),
                        (6, 'Hilo dental vegano', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/hilodental_Orlando2.png', 3, null),
                        (7, 'Toallitas Femeninas de Tela color blanco', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/toallitas-femeninas-de-tela-normal-natural.jpg', 4, null),
                        (8, 'Toallitas femeninas de color azul y blanco', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/toallitas_tela.png', 4, null),
                        (9, 'Cepillo de dientes, vista frontal', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/cepillo_meraki.jpg', 5, null),
                        (10, 'Cepillo de dientes, vista lateral', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/cepillo_meraki_2.png', 5, null),
                        (11, 'Afeitadora de paja de trigo', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/afeitadora_trigo.png', 6, null),
                        (12, 'Afeitadora de paja de trigo', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/afeitadora_trigo2.png', 6, null),
                        (13, 'Juego de vajilla biodegradable de 6 piezas, color verde pastel', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/juego_vajilla.png', 7, null),
                        (14, 'Juego de vajilla biodegradable de 6 piezas, color salmón', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/juego_vajilla_2.png', 7, null),
                        (15, 'Pack de sorbetes reutilizables en envase 100% biodegradable', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/sorbetereutilizable_oregon.jp', 8, null),
                        (16, 'Pack de sorbetes reutilizables en envase 100% biodegradable', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/sorbetesreutilizable_2.jpeg', 8, null),
                        (17, 'Envoltura sustentable de alimentos con estampado blanco y celeste', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/envoltorio_beegreen.jpg', 9, null),
                        (18, 'Envoltura sustentable de alimentos con estampado de hojas', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/envoltorio-sustentable.png', 9, null),
                        (19, 'Bolsas de residuos biodegradables, su caja contenedora de cartón y el dispensador con forma de hueso', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/bolsa_mascota.png', 10, null),
                        (20, 'Dispensador bolsas de residuos con forma de hueso', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/bolsas-residuos-2.jp', 10, null),
                        (21, 'Plato para mascotas color rojo', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/plato_mascota.png', 11, null),
                        (22, 'Plato para mascotas color azul', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/plato_mascotas_2.jpg', 11, null),
                        (23, 'Jabón y Champú sólido para perros con forma rectangular, vista frontal', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/champu-solido-para-perros-.jpg', 12, null),
                        (24, 'Jabón y Champú sólido para perros con forma rectangular, vista lateral', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/champu-solido-para-perros-2.jpg', 12, null),
                        (25, 'Cucha de perro de color blanco', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/cucha_perros.jpg', 13, null),
                        (26, 'Cucha de perro de color blanco con perro sonriente dentro', 'https://raw.githubusercontent.com/PPROF2-2022ProgWeb/g27-aula1-tiendaonline-g27/main/GreenBuddies/src/assets/img/cucha_perro_2.jp', 13, null);
                        
                        
                           
                           
                         